#lang br/quicklang
(require ".rkt")

; this macro extracts the particle count, center, and velocity
; from a system definition, and creates a system object (list of particles)
(define-macro (system-defn ID FEATURE ...)
  (with-pattern
      ([P-COUNT (find-property 'particles #'(FEATURE ...))]
       [CENTER (find-property 'center #'(FEATURE ...))]
       [VELOCITY (find-property 'velocity #'(FEATURE ...))]
       [MASS (find-property 'mass #'(FEATURE ...))])
    #'(system P-COUNT
              CENTER
              VELOCITY
              MASS))) ; notice the contract between system and this macro!

; this macro extracts the size and time for the simulation
(define-macro (sim-defn FEATURE ...)
  (with-pattern
      ([SIZE (find-property 'size #'(FEATURE ...))]
       [TIME (find-property 'size #'(FEATURE ...))])
    #'(list SIZE TIME))) ; notice the contract between this output and the simulation module!


; this macro:
;   1) creates the particles list
;   2) creates the simulation parameters
;   3) calls simulate from the simulation module
(define-macro (particool-begin (simulation DEFN ...))
  (with-pattern
      ([(SYSTEM-DEFN ...) (find-definitions 'system-defn #'(DEFN ...))] ; extract system-defns
       [(SIM-DEFN ...) (find-definitions 'sim-defn #'(DEFN ...))])      ; extrace sim-defns
    #'(#%module-begin
       ; each system-defn returns lists of particles
       (define particles (append SYSTEM-DEFN ...))
       ; "each" sim-defn defines key traits of the simulation
       (define sim-features (append SIM-DEFN ...))
       (define world (list sim-features particles))
       (simulate world) ; call out to simulation.rkt
       )))

(provide (rename-out [particool-begin #%module-begin]))
(provide system-defn sim-defn simulate system vector)


; system: returns a list of particles clustered
;   around center with given velocity
; golden-angle offset logic generated by Claude AI
(define (system num-particles center velocity total-mass)
  (define golden-angle 2.399963) ; radians, ~137.5°
  (for/fold ([particles '()])
            ([i (in-range num-particles)])
    (define r (* 5 (sqrt i)))          ; spread outward as sqrt(i)
    (define theta (* i golden-angle))  ; rotate by golden angle each step
    (define offset (vector (* r (cos theta)) (* r (sin theta))))
    (define p (particle (vector-map + center offset) velocity total-mass))
    (cons p particles)))

