#lang br/quicklang
(provide (matching-identifiers-out #rx"^" (all-defined-out))) ; provides all macros/functions starting with "rsnd-"

(require "playback.rkt")
(define instruction-counter 0) 

;(define-macro (inst-details ID STRUM ...)
;  (with-pattern
;      ([REFERENCE ID]
;;       [TYPE STRUM]) 
;    #'(inst REFERENCE
;              TYPE)))

;(define-macro (find-order instructs ...)
 ; (with-pattern
      ;find all parser instructions
      ;order them in a list
      ;oooo


(define-macro (rsnd-program INSTRUCTS ...)
  (with-pattern
      ([((inst NAME TYPE) ...) #'(INSTRUCTS ...)]
       [((play INST NOTE) ...) #'(INSTRUCTS ...)]
       )
    #'(#%module-begin
       INSTRUCTS ...
       (define instruments
         (apply hasheq (append (list NAME TYPE) ...)))
       (define notes
         (list (INST NOTE) ...))
       (playback instruments notes)
       )))
   

(provide (rename-out [rsnd-program #%module-begin]))
;(provide system-defn sim-defn simulate system vector)


; system: returns a list of particles clustered
;   around center with given velocity
; golden-angle offset logic generated by Claude AI
;(define (system num-particles center velocity total-mass)
 ; (define golden-angle 2.399963) ; radians, ~137.5°
  ;(for/fold ([particles '()])
   ;         ([i (in-range num-particles)])
    ;(define r (* 5 (sqrt i)))          ; spread outward as sqrt(i)
    ;(define theta (* i golden-angle))  ; rotate by golden angle each step
   ; (define offset (vector (* r (cos theta)) (* r (sin theta))))
   ; (define p (particle (vector-map + center offset) velocity total-mass))
    ;(cons p particles)))


; syntax helpers

;(begin-help-assemble-instructions
;  (require racket)
;  (define (in-order-assemble lst arg)
;    (


(begin-for-syntax
  (require racket/list)

  (define (unique-ids stxs)
    (remove-duplicates stxs #:key syntax->datum))
  
  (define (find-property which line-stxs) ; adapted from BR's basic find-property, used Claude AI
    (for/first ([stx (in-list (syntax->list line-stxs))]
                #:when (eq? which (syntax->datum (car (syntax->list stx)))))
      (cadr (syntax->list stx))))

  (define (find-definitions which line-stxs)
    (for/list ([stx (in-list (syntax->list line-stxs))]
               #:when (and (syntax->list stx)
                           (eq? which (syntax->datum (car (syntax->list stx))))))
      stx)))